import org.gradle.api.DefaultTask
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.TaskAction
import java.io.File

abstract class GenerateIosConfigTask : DefaultTask() {
    @get:Input
    abstract val outputDir: Property<String>

    @get:Input
    abstract val teamId: Property<String>

    @get:Input
    abstract val productName: Property<String>

    @get:Input
    abstract val bundleId: Property<String>

    @get:Input
    abstract val displayName: Property<String>

    @get:Input
    abstract val versionCode: Property<String>

    @get:Input
    abstract val versionName: Property<String>

    @TaskAction
    fun generate() {
        val outputFile = File(outputDir.get(), "Config.xcconfig")
        outputFile.parentFile.mkdirs()

        val teamIdValue = teamId.getOrElse("")
        val productNameValue = productName.getOrElse("Template")
        val bundleIdValue = bundleId.getOrElse("btk.digital.app")
        val displayNameValue = displayName.getOrElse("Template")
        val versionCodeValue = versionCode.getOrElse("10000")
        val versionNameValue = versionName.getOrElse("1.0.0")

        // Check if the properties were actually present
        if (!bundleId.isPresent || !versionCode.isPresent || !versionName.isPresent) {
            logger.warn(
                """
                Warning: Some properties not found in gradle.properties. Using default values.
                """.trimIndent()
            )
        }

        outputFile.writeText(
            """
            // Auto-generated by Gradle — do not edit manually
            TEAM_ID=$teamIdValue
            PRODUCT_NAME=$productNameValue
            
            PRODUCT_BUNDLE_IDENTIFIER[config=Debug]=$bundleIdValue.debug
            PRODUCT_BUNDLE_IDENTIFIER[config=Release]=$bundleIdValue

            BUNDLE_DISPLAY_NAME[config=Debug]=$displayNameValue Debug
            BUNDLE_DISPLAY_NAME[config=Release]=$displayNameValue

            CURRENT_PROJECT_VERSION=$versionCodeValue
            MARKETING_VERSION=$versionNameValue
            
            """.trimIndent()
        )

        println("Generated iOS config: ${outputFile.absolutePath}")
    }
}