import org.gradle.api.DefaultTask
import org.gradle.api.Project
import org.gradle.api.Task
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.CacheableTask
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.TaskAction
import org.gradle.api.tasks.TaskProvider
import org.gradle.kotlin.dsl.register

@CacheableTask
abstract class GenerateIosConfigTask : DefaultTask() {
    @get:Input abstract val teamId: Property<String>
    @get:Input abstract val productName: Property<String>
    @get:Input abstract val bundleId: Property<String>
    @get:Input abstract val displayName: Property<String>
    @get:Input abstract val versionCode: Property<String>
    @get:Input abstract val versionName: Property<String>

    @get:OutputFile
    abstract val xcconfig: RegularFileProperty

    @TaskAction
    fun generate() {
        val outputFile = xcconfig.get().asFile
        outputFile.parentFile.mkdirs()

        val teamIdValue = teamId.getOrElse("")
        val productNameValue = productName.getOrElse("Template")
        val bundleIdValue = bundleId.getOrElse("btk.digital.app")
        val displayNameValue = displayName.getOrElse("Template")
        val versionCodeValue = versionCode.getOrElse("10000")
        val versionNameValue = versionName.getOrElse("1.0.0")

        val content =
            """
            // Auto-generated by Gradle — do not edit manually
            TEAM_ID=$teamIdValue
            PRODUCT_NAME=$productNameValue
            
            PRODUCT_BUNDLE_IDENTIFIER[config=Debug]=$bundleIdValue.debug
            PRODUCT_BUNDLE_IDENTIFIER[config=Release]=$bundleIdValue

            BUNDLE_DISPLAY_NAME[config=Debug]=$displayNameValue Debug
            BUNDLE_DISPLAY_NAME[config=Release]=$displayNameValue

            CURRENT_PROJECT_VERSION=$versionCodeValue
            MARKETING_VERSION=$versionNameValue
            
            """.trimIndent()

        if (outputFile.exists() && outputFile.readText() == content) return

        outputFile.writeText(content)
        println("Generated iOS config: ${outputFile.absolutePath}")
    }
}

fun Project.registerGeneratorIosConfig() {
    val generateIosConfig = tasks.register<GenerateIosConfigTask>("generateIosConfig") {
        xcconfig.set(layout.projectDirectory.file("iosApp/Configuration/Config.xcconfig"))
        teamId.set(providers.gradleProperty("ios.team.id"))
        productName.set(providers.gradleProperty("ios.product.name"))
        bundleId.set(providers.gradleProperty("app.id"))
        displayName.set(providers.gradleProperty("app.display.name"))
        versionCode.set(providers.gradleProperty("version.code"))
        versionName.set(providers.gradleProperty("version.name"))

        listOf(teamId, productName, bundleId, displayName, versionCode, versionName)
            .forEach { it.finalizeValueOnRead() }
    }

    dependsIfExists(name = "build", task = generateIosConfig)
    dependsIfExists(name = "assemble", task = generateIosConfig)
}

fun Project.dependsIfExists(name: String, task: TaskProvider<out Task>) {
    tasks.matching { it.name.contains(name, ignoreCase = true) }.configureEach {
        dependsOn(task)
    }
}